/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aula.debugando.remoto;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class AppIntTest {
    @Test public void testSlowMethod() throws InterruptedException {
        new App().slowMethod();
    }
}
